version: "3.7"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tuGerente
    restart: always
  web:
    build: ./server
    environment:
      MYSQL_DATABASE: tuGerente
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
